create table "public"."organization" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "slug" character varying not null,
    "created_by" uuid not null,
    "public_metadata" json,
    "private_metadata" json,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."organization" enable row level security;

CREATE UNIQUE INDEX organization_pkey ON public.organization USING btree (id);

CREATE UNIQUE INDEX organization_slug_key ON public.organization USING btree (slug);

CREATE INDEX organization_slug_idx ON public.organization USING btree (slug);

alter table "public"."organization" add constraint "organization_pkey" PRIMARY KEY using index "organization_pkey";

alter table "public"."organization" add constraint "organization_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."organization" validate constraint "organization_created_by_fkey";

alter table "public"."organization" add constraint "organization_slug_key" UNIQUE using index "organization_slug_key";